apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paniten-bot.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paniten-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.telegram.botToken }}
  BOT_TOKEN: {{ .Values.telegram.botToken | quote }}
  {{- else }}
  {{- fail "telegram.botToken is required" }}
  {{- end }}
  {{- if .Values.webhook.secret }}
  WEBHOOK_SECRET: {{ .Values.webhook.secret | quote }}
  {{- else }}
  {{- fail "webhook.secret is required" }}
  {{- end }}
  {{- if .Values.telegram.authorizedUsers }}
  AUTHORIZED_USERS: {{ .Values.telegram.authorizedUsers | quote }}
  {{- else }}
  {{- fail "telegram.authorizedUsers is required" }}
  {{- end }}
  {{- if .Values.telegram.chatId }}
  CHAT_ID: {{ .Values.telegram.chatId | quote }}
  {{- else }}
  {{- fail "telegram.chatId is required" }}
  {{- end }}