replicaCount: 1

image:
  repository: vourteen14/paniten-bot
  tag: "latest"
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

telegram:
  botToken: ""
  chatId: ""
  authorizedUsers: ""

webhook:
  secret: ""

config:
  nodeEnv: "production"
  databasePath: "/app/data/alerts.db"
  port: 3000
  host: "0.0.0.0"
  logLevel: "info"
  telegramTimeout: 60000
  webhookTimeout: 30000

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: paniten.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""
  accessMode: ReadWriteOnce

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  fsGroup: 1001

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1001
  capabilities:
    drop:
    - ALL

livenessProbe:
  httpGet:
    path: /api/health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /api/health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

serviceAccount:
  create: false
  annotations: {}
  name: ""